# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/hydro_colors',
                'doc_host': 'https://nesar.github.io',
                'git_url': 'https://github.com/nesar/hydro_colors',
                'lib_path': 'hydro_colors'},
  'syms': {'hydro_colors.core': {'hydro_colors.core.foo': ('core.html#foo', 'hydro_colors/core.py')}}}
