# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/hydro_colors',
                'doc_host': 'https://nesar.github.io',
                'git_url': 'https://github.com/nesar/hydro_colors',
                'lib_path': 'hydro_colors'},
  'syms': { 'hydro_colors.core': { 'hydro_colors.core._convert_age': ( 'load_hacc_gal_stellar_catalog.html#_convert_age',
                                                                       'hydro_colors/core.py'),
                                   'hydro_colors.core._convert_metallicity': ( 'load_hacc_gal_stellar_catalog.html#_convert_metallicity',
                                                                               'hydro_colors/core.py'),
                                   'hydro_colors.core.load_fsps_spectral_library': ( 'load_hacc_gal_stellar_catalog.html#load_fsps_spectral_library',
                                                                                     'hydro_colors/core.py')}}}
