# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_calculate_csp.ipynb.

# %% auto 0
__all__ = ['total_luminosity', 'galaxy_stellar_mass', 'ssp_to_csp', 'calc_fluxes_for_galaxy']

# %% ../nbs/03_calculate_csp.ipynb 3
import numpy as np
from .ssp_interpolation import spec_ssp_lookup

from .load_sps_library import load_fsps_spectral_library, load_fsps_age_metallicity
from .load_sps_library import STELLAR_LIBRARY_DIR

from .load_sim_stellar_catalog import load_hacc_galaxy_data
from .load_sim_stellar_catalog import GALS_DIR, GALS_FILE
from .load_sim_stellar_catalog import Z_SOLAR_PADOVA, H0

# %% ../nbs/03_calculate_csp.ipynb 4
def total_luminosity(spec_flux_ssp:np.ndarray, # SSP SEDs   
                     spec_wave:np.array # SED Wavelength
                    )-> np.float32: #Luminosity
    flux_proxy = np.trapz(spec_flux_ssp, spec_wave, axis=1) 
    return flux_proxy


def galaxy_stellar_mass(selected_star_masses:np.array #SSP masses in a galaxy
                       )-> np.float32: # Total stellar mass of the galaxy
    
    gal_stellar_mass = np.sum(selected_star_masses)
    return gal_stellar_mass


def ssp_to_csp(spec_flux_ssp:np.ndarray # SSP SEDs
              )-> np.array: #CSP SED
    spec_csp = np.sum(spec_flux_ssp, axis=0) ## CSP
    return spec_csp

# %% ../nbs/03_calculate_csp.ipynb 5
def calc_fluxes_for_galaxy(gal_file_in:str=GALS_DIR+GALS_FILE, # HACC stellar catalog
                           unique_gal_tag:np.float32=None, # Selected galaxy tag
                           spectral_library_path:str=STELLAR_LIBRARY_DIR, # Spectral library path
                          )->tuple: # SED wavelength, individual SSP SEDs, CSP SED, Luminosity, Galaxy stellar mass  
    
    spec_flux_library, spec_wave_library = load_fsps_spectral_library(spectral_library_path)
    age_fsps_gyr, Z_padova_fsps = load_fsps_age_metallicity(spectral_library_path)
    gal_tags, _, metal_hydro, mass, age_hydro, _, _, _ = load_hacc_galaxy_data(gal_file_in)


    gal_tag_cond = np.where(gal_tags == unique_gal_tag)

    spec_flux_ssp = np.zeros( shape=(gal_tag_cond[0].shape[0], spec_wave_library.shape[0]))

    for idx, ssp_id in enumerate(gal_tag_cond[0]):    
        spec_wave_ssp, spec_flux_ssp[idx] = spec_ssp_lookup(age_hydro[ssp_id], 
                                                            metal_hydro[ssp_id], 
                                                            mass[ssp_id],
                                                            age_fsps_gyr,
                                                            Z_padova_fsps,
                                                            spec_flux_library,
                                                            spec_wave_library)

    spec_csp = ssp_to_csp(spec_flux_ssp)
    flux_proxy = total_luminosity(spec_flux_ssp, spec_wave_library) 
    gal_stellar_mass = galaxy_stellar_mass(mass[gal_tag_cond])

    return spec_wave_ssp, spec_flux_ssp, spec_csp, flux_proxy, gal_stellar_mass 
