# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_cosmic_dimming.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/05_cosmic_dimming.ipynb 3
import numpy as np
from .ssp_interpolation import spec_ssp_lookup

from .load_sps_library import load_fsps_spectral_library, load_fsps_age_metallicity
from .load_sps_library import STELLAR_LIBRARY_DIR

from .load_sim_stellar_catalog import load_hacc_galaxy_data
from .load_sim_stellar_catalog import GALS_DIR, GALS_FILE
from .load_sim_stellar_catalog import Z_SOLAR_PADOVA, H0

from .calculate_csp import calc_fluxes_for_galaxy
