# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_dust_attenuation.ipynb.

# %% auto 0
__all__ = ['total_luminosity', 'galaxy_stellar_mass', 'ssp_to_csp']

# %% ../nbs/04_dust_attenuation.ipynb 3
import numpy as np

# %% ../nbs/04_dust_attenuation.ipynb 5
from .load_sim_stellar_catalog import load_hacc_galaxy_data
from .calculate_csp import calc_fluxes_for_galaxy
from .load_sps_library import STELLAR_LIBRARY_DIR

# %% ../nbs/04_dust_attenuation.ipynb 10
def total_luminosity(spec_flux_ssp:np.ndarray, # SSP SEDs   
                     spec_wave:np.array # SED Wavelength
                    )-> np.float32: #Luminosity
    flux_proxy = np.trapz(spec_flux_ssp, spec_wave, axis=1) 
    return flux_proxy


def galaxy_stellar_mass(selected_star_masses:np.array #SSP masses in a galaxy
                       )-> np.float32: # Total stellar mass of the galaxy
    
    gal_stellar_mass = np.sum(selected_star_masses)
    return gal_stellar_mass


def ssp_to_csp(spec_flux_ssp:np.ndarray # SSP SEDs
              )-> np.array: #CSP SED
    spec_csp = np.sum(spec_flux_ssp, axis=0) ## CSP
    return spec_csp
