# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_dust_attenuation.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/04_dust_attenuation.ipynb 3
import numpy as np

# %% ../nbs/04_dust_attenuation.ipynb 5
from .load_sim_stellar_catalog import load_hacc_galaxy_data
from .calculate_csp import calc_fluxes_for_galaxy
from .load_sps_library import STELLAR_LIBRARY_DIR
