# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_load_sps_library.ipynb.

# %% auto 0
__all__ = ['load_fsps_spectral_library', 'load_fsps_age_metallicity']

# %% ../nbs/00_load_sps_library.ipynb 3
import numpy as np
import os
import matplotlib.pylab as plt

# %% ../nbs/00_load_sps_library.ipynb 4
def load_fsps_spectral_library(dirIn = '/lcrc/project/cosmo_ai/nramachandra/Projects/SPHEREx/MAH/nersc_data/portal.nersc.gov/project/hacc/aphearin/dsps_data/FSPS_ssp_data'
): 
    spec_flux = np.load(os.path.join(dirIn, "ssp_spec_flux_lines.npy"))
    spec_wave = np.load(os.path.join(dirIn, "ssp_spec_wave.npy"))
    print('Library shape: ', spec_flux.shape) 
    print('Wavelength shape: ', spec_wave.shape)
    return spec_flux, spec_wave

# %% ../nbs/00_load_sps_library.ipynb 5
def _load_fsps_age(dirIn):
    log_age_gyr = np.load(os.path.join(dirIn, "log_age.npy")) - 9
    age_fsps_gyr = 10**log_age_gyr
    ## (age is in 1/H0 units)
    return age_fsps_gyr

# %% ../nbs/00_load_sps_library.ipynb 6
def _load_fsps_metallicity(dirIn, Z_solar):
    Z_legend = np.load(os.path.join(dirIn, "zlegend.npy"))
    Z_padova = Z_legend/Z_solar
    return Z_padova

# %% ../nbs/00_load_sps_library.ipynb 7
def load_fsps_age_metallicity(dirIn = '/lcrc/project/cosmo_ai/nramachandra/Projects/SPHEREx/MAH/nersc_data/portal.nersc.gov/project/hacc/aphearin/dsps_data/FSPS_ssp_data'):
    
    age_fsps_gyr = _load_fsps_age(dirIn)
    
    Z_solar_padova = 0.019
    Z_padova = _load_fsps_metallicity(dirIn, Z_solar_padova)
    
    return age_fsps_gyr, Z_padova
