# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_ssp_interpolation.ipynb.

# %% auto 0
__all__ = ['spec_ssp_lookup']

# %% ../nbs/02_ssp_interpolation.ipynb 3
import numpy as np

# %% ../nbs/02_ssp_interpolation.ipynb 4
def spec_ssp_lookup(age_hydro_i:np.float32=None, # Age of the HACC stellar particle
             metal_hydro_i:np.float32=None, # Metallicity of the stellar particle
             mass_hydro_i:np.float32=None, # Mass of the stellar particle
             age_fsps:np.float32=None, # Ages in SPS library
             z_padova_fsps:np.float32=None, # Metallicities in SPS library
             spec_flux:np.array=None, # Stellar library SEDs 
             spec_wave:np.array=None, # Stellar library wavelengths
            )-> tuple: # SSP Wavelength, SSP Luminosity 
    '''
    Lookup table for finding the closest SPS entry to HACC SSP
    '''
    # https://ned.ipac.caltech.edu/level5/Sept14/Conroy/Conroy2.html
    
    age_index = np.argmin(np.abs(age_fsps-age_hydro_i))
    met_index = np.argmin(np.abs(z_padova_fsps-metal_hydro_i))
    # print(age_index, met_index)
    
    return spec_wave, mass_hydro_i*spec_flux[met_index, age_index]
